server:
  forward-headers-strategy: framework
  port: 0
spring:
  application:
    name: auth-service
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/