server:
  forward-headers-strategy: framework
  port: 0
spring:
  application:
    name: auth-service
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
keycloak:
  server-url: http://localhost:8080
  realm: master
  username: admin
  password: admin
  client-id: admin-cli
  target-client-id: social-app
  client-secret: TYHG1gwTQscDjrJH9AaNEwteq7xGUwDu
  target-realm: social-app
  api-url: http://localhost:8080/realms/social-app
