server:
  forward-headers-strategy: framework
  port: 0
spring:
  application:
    name: user-service
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: chat-app
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  data:
    mongodb:
      #      authentication-database: admin
      #      host: localhost
      #      username: root
      #      password: root
      #      database: product-db
      #      port: 27017
      uri: mongodb://localhost:27017/user?replicaSet=rs0
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.mongodb.driver: INFO