server:
  port: 9093

swagger:
  config:
    refreshrate: 50000

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF

spring:
  application:
    name: documentation-application

application-description: @project.description@
application-version: v1.1.1
# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/