server:
  forward-headers-strategy: framework
  port: 0
spring:
  application:
    name: conversation-service
  data:
    mongodb:
      #      authentication-database: admin
      #      host: localhost
      #      username: root
      #      password: root
      #      database: product-db
      #      port: 27017
      uri: mongodb://localhost:27017/conversation?replicaSet=rs0
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
